services:
  app:
    # build:
    #   context: .
    #   args:
    #     NEXT_PUBLIC_LIVEKIT_URL: ${NEXT_PUBLIC_LIVEKIT_URL:-}
    #     NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL:-}
    #     NEXT_PUBLIC_ASSETS_DIR: ${NEXT_PUBLIC_ASSETS_DIR:-}
    #     NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-}
    #     NEXT_PUBLIC_SPEAKING_USE_LOCAL_TOKEN_ROUTE: ${NEXT_PUBLIC_SPEAKING_USE_LOCAL_TOKEN_ROUTE:-}
    image: ghcr.io/ziiyodullayevv/mock4ielts:latest
    container_name: mock4ielts
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
      LIVEKIT_URL: ${LIVEKIT_URL:-}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY:-}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET:-}
      LIVEKIT_AGENT_NAME: ${LIVEKIT_AGENT_NAME:-}
      NEXT_PUBLIC_LIVEKIT_URL: ${NEXT_PUBLIC_LIVEKIT_URL:-}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL:-}
      NEXT_PUBLIC_ASSETS_DIR: ${NEXT_PUBLIC_ASSETS_DIR:-}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-}
      NEXT_PUBLIC_SPEAKING_USE_LOCAL_TOKEN_ROUTE: ${NEXT_PUBLIC_SPEAKING_USE_LOCAL_TOKEN_ROUTE:-}
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:3000']
      interval: 30s
      timeout: 5s
      retries: 3
